### ISSUE TITLE
HTML EDIT [OPEN]

### ISSUE THREAD

**Issue by Fryghtened** [camuschat/camus#40]
Heya guys Fry here so i just got into using camus and I LOVE IT. The only part of don't like is that i am not able to change the html of the webapp like for example below 
<img width="665" alt="Pic" src="https://user-images.githubusercontent.com/78953971/114277418-bdf1df00-9a48-11eb-9694-b21f91af3dba.png">
I would love to change the html here !
Anyone know how to?

**Comment by mrgnr** [comment]
@Fryghtened The HTML for the landing page is generated by the server using [this template](https://github.com/mrgnr/camus/blob/master/camus/templates/chat.html). Once inside a room, everything is rendered by React -- you can find the components [here](https://github.com/mrgnr/camus/tree/master/camus/static/js/components).
