### ISSUE TITLE
Peer to Peer Connection not establishing

### ISSUE THREAD

**Issue by waqarland** [camuschat/camus#47]
When I create a room on CAMUS and then share the link to another peer (B), the B person does not show on my side and vice versa. And a Major Tom person appears however nobody has named himself as Major Tom on both peers
Screen shots are attached below

![Screenshot (21)](https://user-images.githubusercontent.com/51796902/116364040-36b0b380-a81d-11eb-81e8-42b8e11ab37b.png)
![Screenshot (22)](https://user-images.githubusercontent.com/51796902/116364049-39aba400-a81d-11eb-8188-6489f09cc84e.png)

 sides

**Comment by mrgnr** [comment]
Thanks for reporting this @waqarland. The server logs showed several errors related to the database, which seems to be the cause of this issue. I've opened https://github.com/camuschat/camus/pull/51 as a fix.
